package HelloApp;


/**
* HelloApp/amountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Sunday, 4 February, 2018 2:20:36 AM IST
*/

public final class amountHolder implements org.omg.CORBA.portable.Streamable
{
  public double value[] = null;

  public amountHolder ()
  {
  }

  public amountHolder (double[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.amountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.amountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.amountHelper.type ();
  }

}
