package HelloApp;


/**
* HelloApp/availablemlHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Sunday, 4 February, 2018 2:20:36 AM IST
*/

public final class availablemlHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public availablemlHolder ()
  {
  }

  public availablemlHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.availablemlHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.availablemlHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.availablemlHelper.type ();
  }

}
