package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Sunday, 4 February, 2018 2:20:36 AM IST
*/

public interface HelloOperations 
{
  String sign (double choice);
  String revoke (double cho);
  String[] playerDetails ();
  double[] getAmt ();
  String[] avail ();
  void shutdown ();
} // interface HelloOperations
